[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+avx,+avx2"]

[alias]
clean-spv = "run -p openinfer-generator --bin clean_spv"
build-spv = "run -p openinfer-generator --bin build_spv"
build-opspec = "run -p openinfer-generator --bin build_opspec"
clean-opspec = "run -p openinfer-generator --bin clean_opspec"