[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+avx,+avx2"]

[alias]
clean-spv = "run --manifest-path openinfer-simulator/generator/Cargo.toml --bin clean_spv"
build-spv = "run --manifest-path openinfer-simulator/generator/Cargo.toml --bin build_spv"
build-opspec = "run --manifest-path openinfer-simulator/generator/Cargo.toml --bin build_opspec"
clean-opspec = "run --manifest-path openinfer-simulator/generator/Cargo.toml --bin clean_opspec"